version: '3'
services:
  get_version:
    container_name: get_version
    image: rclone/rclone:latest
    command: version

  list_remotes:
    container_name: list_remotes
    image: rclone/rclone:latest
    volumes:
      - ./config:/config/rclone
      - harmony_dbs:/data
    command: listremotes
    
  get_db_size:
    container_name: size
    image: rclone/rclone:latest
    volumes:
      - ./config:/config/rclone
    entrypoint:
      - rclone
      - size
      - release:pub.harmony.one/${NETWORK}.${DB_TYPE:-min}/harmony_db_${SHARD}

  clone_harmony_db:
    container_name: clone_harmony_db
    image: rclone/rclone:latest
    volumes:
      - ./config:/config/rclone
      - harmony_dbs:/data
    entrypoint: 
      - rclone
      - -P
      - -L
      - --checksum
      - sync
      - release:pub.harmony.one/${NETWORK}.${DB_TYPE:-min}/harmony_db_${SHARD}
      - harmony_db_${SHARD}
      - --multi-thread-streams
      - "4"
      - --transfers=32
volumes:
  harmony_dbs:
    external: true
