version: '3'
services:
  generate_conf:
    container_name: generate_conf
    image: valyd8chain/harmony-node:latest
    volumes:
      - ../../config:/harmony_node/config
    entrypoint: 
      - ./harmony
      - "config"
      - "dump"
      - "--network"
      - "mainnet" # mainnet or testnet
      - "./config/harmony.conf"
  get_version:
    container_name: get_version
    image: valyd8chain/harmony-node:latest
    entrypoint: 
      - ./harmony
      - "version"