version: '3'
services:
  get_version:
    container_name: get_version
    image: rclone/rclone:latest
    command: version
  list_remotes:
    container_name: list_remotes
    image: rclone/rclone:latest
    volumes:
      - ./config:/config/rclone
      - ./data:/data
    command: listremotes
  clone_harmony_db:
    container_name: clone_harmony_db
    image: rclone/rclone:latest
    volumes:
      - ./config:/config/rclone
      - ./data:/data
    entrypoint: 
      - rclone
      - -P
      - -L
      - --checksum
      - sync
      - release:pub.harmony.one/${NETWORK}.min/harmony_db_${SHARD}
      - harmony_db_${SHARD}
      - --multi-thread-streams
      - "4"
      - --transfers=32