version: '3'
services:
  create_bls_key:
    container_name: create_bls_key
    build: ../../
    volumes:
      - ./blskeys:/harmony_node/.hmy/blskeys
    entrypoint:
      - ./hmy
      - keys
      - generate-bls-keys
      - --bls-file-path 
      - --count
      - "1"
      - --shard
      - ${SHARD}
      - --passphrase